### ISSUE TITLE
errors out on interface collection..

### ISSUE THREAD

**Issue by ThomasADavis** [vinted/sonic-exporter#15] opened 2023-10-27 19:31 UTC
Getting this error:

```
root@sw-d8-r11-u36:~# ./sonic-exporter --web.listen-address=:9102
ts=2023-10-27T18:34:31.996Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9102
ts=2023-10-27T18:34:31.996Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9102
ts=2023-10-27T18:34:37.741Z caller=interface_collector.go:129 level=info msg="Starting interface metric scrape"
ts=2023-10-27T18:34:37.741Z caller=hw_collector.go:123 level=info msg="Starting hw metric scrape"
ts=2023-10-27T18:34:37.743Z caller=interface_collector.go:118 level=error err="interface counters collection failed: err counters collection failed: value parse failed: strconv.ParseFloat: parsing \"\": invalid syntax"
ts=2023-10-27T18:34:37.745Z caller=hw_collector.go:144 level=info msg="Ending hw metric scrape"
```

This is using Edgecore Sonic.

```
SONiC Software Version: SONiC.Edgecore-SONiC_20230822_033113_ec202111_497
Distribution: Debian 11.7
Kernel: 5.10.0-8-2-amd64
Build commit: b91813523
Build date: Tue Aug 22 10:42:26 UTC 2023
Built by: ubuntu@ip-10-5-1-222

Platform: x86_64-accton_as4630_54npe-r0
HwSKU: Accton-AS4630-54NPE
```

Suggestions?

**Comment by rlebedys** [comment] 2023-11-08 08:27
Hi, this exporter was only tested on Community Sonic, I don't have an EdgeCore Sonic image to test it out so there might be some issues.

I found what the root cause is and will try to release a fix shortly.

**Comment by rlebedys** [comment] 2023-11-08 09:33
Please try using the v0.1.2 release, the issue should be fixed.

**Comment by rlebedys** [comment] 2023-11-08 09:33
@ThomasADavis Please try using the v0.1.2 release, the issue should be fixed.

**Closed** 2023-11-08 14:18 UTC

**Comment by ThomasADavis** [comment] 2023-11-09 20:35
Thanks, it works!
